[package]
name = "u-ai"
version = "0.2.0"
edition = "2021"

[dependencies]
ash = "0.37"
libloading = "0.7"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
libc = "0.2"

[build-dependencies]
cc = "1.0"
