[package]
name = "u-ai"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"

[build-dependencies]
cc = "1.0"
