tokenizer:
  path: "/home/unhidra/U-ai/bpe/tokenizer.json"

paths:
  corpora: "/home/unhidra/U-ai/corpora"

model:
  n_embd: 256
  n_head: 8
  n_layer: 8
  dropout: 0.1

training:
  block_size: 256
  batch_size: 16
  learning_rate: 0.0003
  max_steps: 2000
